// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"github.com/KoteiIto/wire-sample/pkg/repository"
	"github.com/KoteiIto/wire-sample/pkg/service"
)

// Injectors from wire.go:

func InitializeAuthService() *service.AuthService {
	userRepository := repository.NewUserRepository()
	onetimeTokenRepository := repository.NewOnetimeTokenRepository()
	authService := service.NewAuthService(userRepository, onetimeTokenRepository)
	return authService
}
